### ISSUE TITLE
为 demo 页的每个链接加一个 visited 后的样式区别一下

### ISSUE THREAD

**Issue by musicq** [airen/DemoHouse#17]
https://airen.github.io/DemoHouse/

这个页面有很多的 demo 例子，但是往往翻着翻着就忘记看到哪一条了，所以我觉得有应该加一个  `a:visited` 来区别一下是不是看过了

![2016-10-19 9 14 14](https://cloud.githubusercontent.com/assets/8630596/19502020/878bd184-95dc-11e6-9740-63625f2a0d72.png)

**Comment by airen** [comment]
@musicq 谢谢你的建议，这个样式已经添加上去了。
